#!/usr/bin/env bash
# Redirection

apt-get -y update
apt-get -y install nginx
service nginx start
echo Holberton School >> /var/www/html/index.html

sed -i "/^server {/a\
location /redirect_me {\n\t\
return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t\
}" /etc/nginx/sites-available/default
service nginx restart
