#!/usr/bin/env bash
# Redirection

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo echo Holberton School >> /var/www/html/index.html

sudo sed -i s/"^server {"/"server {\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"/1 /etc/nginx/sites-available/default
sudo service nginx restart
