#!/usr/bin/env bash
# Redirection

apt-get -y update
apt-get -y install nginx
service nginx start
echo Holberton School >> /var/www/html/index.html

sed -i s/"^server {"/"server {\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"/1 /etc/nginx/sites-available/default
service nginx restart
