#!/usr/bin/env bash
#Create the file containing its PID, display "To infinity and beyond" indefinitely, display "I hate the kill command" when receiving a SIGTERM signal, display "Y U no love me?!" when receiving a SIGINT signal and delete the file on signal.

file=/var/run/holbertonscript.pid
touch $file
trap 'echo I hate the kill command; rm -f $file' SIGTERM
trap "echo Y U no love me?!" SIGINT
trap 'rm -f '$file'; exit' SIGQUIT

while :
do
	echo "To infinity and beyond"
	sleep 2
done
exit 0
