#!/usr/bin/env bash
#displays "To infinity and beyond" indefinitely with a "sleep 2" and display "I am invicible!!! when receiving a SIGTERM signal.

trap "echo I am invincible!!!" SIGTERM

while :
do
	echo "To infinity and beyond"
	sleep 2
done
exit 0
