#!/usr/bin/env bash
#

IFS=:
while read -r user passwd uid gid root home_dir user_shell;
do
	echo "The user $user is part of the $gid gang, lives in $home_dir and rides $user_shell. $uid's place is protected by the passcode $passwd, more info about the user here: $root"
done < /etc/passwd
