#!/usr/bin/env bash
#display Holberton School 10 times, but after the 9th iteration, display Hi once.

a=1
while [ $a -lt 11 ]
do
	if [ $a == 10 ]
	then
		echo "Hi"
	fi
	echo $"Holberton School"
	a=$((a + 1))
done
