#!/usr/bin/env bash
#loop from 1 to 10 and display "bad luck" for the 4th loop iteration and "good luck" for the 8th loop iteration, else display "Holberton School.

a=1
while [ $a -lt 11 ]
do
	
	if [ $a == 4 ]
	then
		echo "bad luck"
	elif [ $a == 8 ]
	then
		echo "good luck"
	else
		echo $"Holberton School"
	fi
	a=$((a + 1))
done
