#!/usr/bin/env bash
#display numbers from 1 to 20. After the 4th iteration, display "bad luck from China", after 9th loop iteration, display "bad luck from Japan", after 17th loop iteration, display "bad luck from Italy", else display numbers.

a=1
while [ $a -lt 21 ]
do 
	case $a in
		4)
			echo "$a"
			echo "bad luck from China";;
		9)
			echo "$a"
			echo "bad luck from Japan";;
		17)
			echo "$a"
			echo "bad luck from Italy";;
		*)
	echo "$a";;
	esac
	a=$((a+1))
done
