#!/usr/bin/env bash
#display the time for 12 hours and 59 minutes. Display hours from 0 to 12 and display minutes from 1 to 59.

a=0
b=1
while [ $a -le 12 ]
do
	echo "Hour: $a"
	while [ $b -le 59 ]
	do
		echo $b
		b=$((b + 1))
	done
	a=$((a + 1))
	b=1
done
